### ISSUE TITLE
One Artboard PNG Export

### ISSUE THREAD

**Issue by Despe-Roddo** [schroef/Photoshop-Scripts#1]
Thanks for this script! 

Having Issues exporting individual PNGs. Even when i select only export one particular artboard, it exports all the artboards in the document.

I noticed it works fine with exporting JPGs abut PNGs only have this issue.

Thanks!

**Comment by schroef** [comment]
Do you have a simple test document for me perhaps?

Sorry for getting back so late, i was without proper working laptop for a couple months. Ill try and see how i can adjust the script if understand your request.

I see what my test documents do in this case.

**Comment by schroef** [comment]
I just tried it and works fine for me. In the screengrab i have 2 artboards and a couple layercomps. In the export menu i choose the layercomp AND the artboard. If you check "single artboard" and dont choose anything it will still do them all. Perhaps i should make that more clear. I think i would nee to change NONE to ALL, thats way its more clear it will actually do all.

![Screen Shot 2020-12-17 at 17 31 08](https://user-images.githubusercontent.com/6923008/102546551-34c82e00-408e-11eb-8b90-995a5856e4a7.png)

EDIT
it actually does work, when it still on NONE in the 'Choose Artboard' it will give an error.

When i select one artboard here it will only spit out that one. Atleast for me it does so. 

Whats your Photoshop version and OS?

**Comment by schroef** [comment]
@Despe-Roddo 
I think i have found your issue, i think i already knew about this but never fixed it. When using transparency or "keep layers" in PSD format it doesnt clean the files. I did some optimizing in the export so files will export faster. But due to that i think i forgot to clean the artboards.

Is the below screengrab around the same you get? So you basically get the exports with the correct export filename you gave, but it contains both artboards with a margin aside in a single image?

![Screen Shot 2020-12-17 at 18 33 41](https://user-images.githubusercontent.com/6923008/102551953-bde36300-4096-11eb-82f8-b111bb941dee.png)
![Screen Shot 2020-12-17 at 18 36 28](https://user-images.githubusercontent.com/6923008/102551987-cb98e880-4096-11eb-810a-2a5242aa42b2.png)

**Comment by schroef** [comment]
Im almost there, its more of an issue then i thought. It runs fine when the image is flattened. But using the transparency feature cause me a headache to find the proper workflow. Really hope i can nail this one.

**Comment by schroef** [comment]
I think i got it working properly now. It took me quite some testing. I also noticed that when i finally got it working on Windows, it still didnt work on OSX. Ive also made huge improvements in speed. The old method used a script which went over layer by layer and would delete if hidden. Ive now made a much faster method. Hide all  others > then delete others. I went from 122 seconds for 4 artboards with 25 layers in total to 20 seconds. This would export 12 layered files.

I do notice Windows is much more sluggish or lagging, but i think thats an issue with PS 2020 or so. The UI is very sluggish and has weird things like artboards Not showing transparent.

Ill upload the new version tonight

**Comment by schroef** [comment]
Okay new version is in, hope it works for you as well

**Comment by Despe-Roddo** [comment]
Apologies for the late response! So not sure if this is a new issue altogether, but I tested this out on the current photoshop update looks like this issue popped up when exporting PNGs:
![image](https://user-images.githubusercontent.com/70179737/105800867-a4aebb80-5f4c-11eb-8810-433fa34a5cbc.png)

I will try to simulate this in a bit

**Comment by Despe-Roddo** [comment]
Hmm so I made a new Test Document and good news it looks like its working properly! 

This is how I set the test up:
![Document](https://user-images.githubusercontent.com/70179737/105802125-6cf54300-5f4f-11eb-9e43-bcaacbe71af7.png)

Although I got this new error, but I don't think it affects anything:
![newerror](https://user-images.githubusercontent.com/70179737/105802186-81d1d680-5f4f-11eb-9321-a8d89d5ef460.png)

And here is my end result:
![result](https://user-images.githubusercontent.com/70179737/105802219-92824c80-5f4f-11eb-83f4-38f4c5e967a8.png)

So I am thinking I got the "Delete" Error because the document I was working on was originally made on an older version of photoshop.

**Comment by schroef** [comment]
Thanks for testing it again. Yeah that color profile "error" is just a warning. I added because i had issues with images not having a profile assigned. 

Do you remember why the first error appeared, the error about "command delete not available". The delete command is not a command from newer version i believe. I mean i worked on this script using 2018cc and worked fine. Could you perhaps show screengrabs + layers panel. Perhaps i can better understand the issue that way.

Ive seen some cases where it still wont run. But i believe items are working smooth now.

**Comment by mfwit** [comment]
I am seeing this issue in CC 2021 on Mac OS as well. Though even when I export in JPG, one of my 5 artboards exports out as all the artboards.

Let me know what you'd like to see that could possibly help diagnose.

**Comment by schroef** [comment]
Could you perhaps share that document?
I dont have 2021 cc on OSX, but i can test it on Windows. I have seen different issues between the different OS's though. Since 2020 or perhaps even earlier, on Windows the UI and kinda the complete photoshop is kinda sluggish. At work i got an old Mac Pro and use 2018 cc and its smooth as butter. Export on OSX go within a couple secconds but due to the sluggish UI on windwos its about 10x slower or so.

@mfwit do you get any error messages?

**Comment by mfwit** [comment]
For sure, here it is: https://www.dropbox.com/s/g1nlsudw9cbejc0/template%20test.psd?dl=0

I tweaked the file a bit and now its behaving a little differently. Just tested exporting as PNG and JPG and here are the results:

PNG
- takes a few minutes to export and PS almost appears frozen while it works
- all files come out as all artboards for the layer comp

JPG
- takes several seconds and I can see PS actively doing things while it works
- all files come out correctly except the igw artboards, which come out as all artboards for the layer comp

Perhaps my igw artboard has an issue of some sort?

Appreciate the help!

**Comment by schroef** [comment]
Thanks for the file. I just tried 2018cc on OSX 10.11.6 and tried first JPG then PNG. JPG was blazing fast with no issues, Then i tried transparent PNG and got an error first time i tried. Then tried it again and it did run just, it did took longer because transparency is always much slower with saving.

PS first time i got this error it also did stop on that IGW artboard. It was something of a type error, not sure ive seen that error before. Ill run it again see if it happens again.
![ouputs-PNG](https://user-images.githubusercontent.com/6923008/132250259-5a588962-ec09-4bac-b4ba-a471b90eb78b.png)
![ouputs-JPG](https://user-images.githubusercontent.com/6923008/132250277-e0638e11-9250-4861-9c23-fd5403f22d5a.png)


PS that are some pretty luxury Escape keys right? Looks nice, are these 3d renderings?

EDIT
Guess they are real photos, just found this [reddit post ](https://www.reddit.com/r/MechanicalKeyboards/comments/ndbr3r/the_super_simple_macropad_by_256klabs/)with more images. Dang that looks beautiful :) Super nice work!

**Comment by mfwit** [comment]
Alright, I'll do some more testing/repetition on my end across a couple different versions and see if I can replicate.

Yea, they are 'artisan keycaps'. Started collecting and subsequently photographing them in the last year. It's a fun but increasingly expensive little hobby. Appreciate the kind works!

**Comment by schroef** [comment]
Really nice man! Just found this girl making key cabs of Kurby, hilarious! But these look super high qulity caps, even bumped into cooper caps. Some stunning octopus cap. I never this existed but such high quality handmade caps. Amazing!

I got the error again, but it seems random. Tried it again, run it a couple times and didnt show again. I did caught the error now, but it showed after the run, the duplicated document also stayed open, it should close.

I also dont understand this error as the run had already been completed. Ill check Windows tonight, see how it runs on that OS.
![TypeError-issue03](https://user-images.githubusercontent.com/6923008/132253334-b3d1445f-c334-4ac1-8c58-5ae3665b44ba.png)


PS so that issue with one of the 5 artboards exported as the complete document is gone?
PS that issue with IGW is nothing. my guess it causeed by something in the script. Its the first artboard in the layer stack yet it looks like the 3rd on the canvas /workarea.

PS 2
If you are going to use these shits, make sure you use sRGB as export profile. But i guess you know all about that as i see your a pretty avid photographer

**Comment by schroef** [comment]
I did found some other issues just now, it seems when a user wants to export single artboards and layercomps, it still seems to have issues expiorting PNG. With PNG i still see all the artboards as 1 document being exported. This doesnt happen when i let it run over all of them. I need to check whats going on, can take some time havent worked in this one for quite a while. So i need to get my head into the flow of this one

**Comment by mfwit** [comment]
No worries. I appreciate the help! I'll let you know if I come across anything else.

PS... my favorite artisan maker at the moment: https://www.instagram.com/archetype_mk/

**Comment by schroef** [comment]
Ill post a new version later tonight. Ive fixed the single export for all flattened versions. Seems i had forgot to put back some stripped code earlier

**Comment by schroef** [comment]
> No worries. I appreciate the help! I'll let you know if I come across anything else.
> 
> PS... my favorite artisan maker at the moment: https://www.instagram.com/archetype_mk/

Wow that looks awesome! Unbelievable how detailed they are. Pretty cool have those blacklight ones. Guess its weird on the eyes sitting in Blacklight with your monitor.

Ive updated it now to version 1.2.2, this fixed the single exports for other then JPG format.
Did you find time to do more testing?

**Comment by mfwit** [comment]
Just did some quick testing with 1.2.2 and it seems to work perfectly aside from that TypeError, which doesn't seem to affect functionality! I will let you know if I run into anything else.

Thanks again!

**Comment by schroef** [comment]
@mfwit i added a couple new feats, would you mind testing it again?

**Comment by mfwit** [comment]
Works like a champ. Very nice update!
